### ISSUE TITLE
Add component addition/removing API to AbstractOrderedLayout + HL & VL

### ISSUE THREAD

**Issue by pleku** [vaadin/flow-legacy-components#10]
<html>
<body>
<google-sheets-html-origin>

Return| Method name
-- | --
void | addComponent(Component c, int index)Adds a component into indexed position in this container.
void | addComponentAsFirst(Component c)Adds a component into this container.
Component | getComponent(int index)Returns the component at the given position.
int | getComponentCount()Gets the number of contained components.
int | getComponentIndex(Component component)Returns the index of the given component.
void | replaceComponent(Component oldComponent, Component newComponent)Replaces the component in the container with another one without changing position.

</body>
</html>

Unit tests should be enough for validation.

**Comment by fhdhsni** [comment]
also `public void removeAll()` and `public void replace(Component oldComponent, Component newComponent)` if we decided to implement `HasOrderedComponents`

**Comment by fhdhsni** [comment]
https://github.com/vaadin/flow-legacy-components/pull/41#discussion_r707095672
