### ISSUE TITLE
Investigate DOM structure and base CSS for Panel

### ISSUE THREAD

**Issue by pleku** [vaadin/flow-legacy-components#28]
We can base it on the scroller web component or just use plain elements - to be decided.

The component introduces some basic CSS that makes it look like it does in v7/v8 with Valo and gives an API to customize it. Feature design doc has some discussion on it
https://docs.google.com/document/d/1EWOErwrpzFYD1zFAHHbxT4SQUna8zl0DxHyLaGDzEeU/edit?pli=1#heading=h.ay6af4v91c50

An example running on version 7.5.5 shows how [the style constants ](https://vaadin.com/api/framework/8.13.3/com/vaadin/ui/themes/ValoTheme.html#PANEL_BORDERLESS) behave https://demo.vaadin.com/valo-theme/#!panels

Outcome of this issue should be:
- the decision on how we build the component DOM structure
- the basic CSS to make it look like legacy Panel
- the CSS that makes the style constants work when applied
- the Valo CSS variables for customizing the look of the component (?)

**Comment by anezthes** [comment]
Source: https://demo.vaadin.com/sampler/#ui/structure/panel

The current DOM structure:
```
<div
  class="v-panel v-widget v-has-width v-has-height"
  style="
    overflow: hidden;
    width: 100%;
    height: 100%;
    padding-top: 38px;
    padding-bottom: 0px;
  "
>
  <div class="v-panel-captionwrap" style="margin-top: -38px">
    <div class="v-panel-caption">
      <span class="v-icon Vaadin-Icons"></span><span>Panel caption</span>
    </div>
  </div>
  <div
    class="v-panel-content v-scrollable"
    tabindex="-1"
    style="position: relative"
  >
    <div
      class="
        v-verticallayout
        v-layout
        v-vertical
        v-widget
        v-has-width
        v-margin-top
        v-margin-right
        v-margin-bottom
        v-margin-left
      "
      style="width: 500px"
    >
      <div class="v-slot">
        <div class="v-label v-widget v-label-undef-w">
          Content
        </div>
      </div>
    </div>
  </div>
  <div class="v-panel-deco" style="margin-bottom: 0px"></div>
</div>
```

**Comment by anezthes** [comment]
Source: https://github.com/vaadin/framework/blob/master/themes/src/main/themes/VAADIN/themes/valo/components/_panel.scss

Panel specific variables:
```
$v-panel-background-color: scale-color(lighten($v-app-background-color, 5%), $saturation: -5%) !default;
$v-panel-border: $v-border !default;
```

Additional variables* that will affect Panel's look one way or another:
```
$v-app-background-color
$v-background-color
$v-bevel
$v-border
$v-border-radius
$v-caption-font-weight;
$v-caption-font-size;
$v-gradient
$v-shadow
$v-unit-size
```
* There's probably more, but these were used in the SCSS file above.
