### ISSUE TITLE
Investigate mapping Valo theme variables to Lumo 

### ISSUE THREAD

**Issue by pleku** [vaadin/flow-legacy-components#51]
Goal would be to map out the Valo theme variables and whether/how we can map those to Lumo theme, so that we can maybe create a "legacy Valo theme" on top of Lumo which allows people to retain their custom theming without porting those to Lumo themselves.

**Comment by anezthes** [comment]
Source: https://vaadin.com/api/valo/

### Color
| Valo | Lumo |
| --- | --- |
| v-background-color | --lumo-xxx |
| v-app-background-color | --lumo-xxx |
| v-font-color | --lumo-xxx |
| v-focus-color | --lumo-xxx |
| v-selection-color | --lumo-xxx |
| v-error-indicator-color | --lumo-xxx |
| v-required-field-indicator-color | --lumo-xxx |
| v-friendly-color | --lumo-xxx |
| v-color-keywords | --lumo-xxx |
| v-luminance-threshold | --lumo-xxx |

### Optimisation
| Valo | Lumo |
| --- | --- |
| v-animations-enabled | --lumo-xxx |
| v-hover-styles-enabled | --lumo-xxx |
| v-included-components | --lumo-xxx |
| v-included-additional-styles | --lumo-xxx |

### Style
| Valo | Lumo |
| --- | --- |
| v-border | --lumo-xxx |
| v-border-radius | --lumo-xxx |
| v-gradient | --lumo-xxx |
| v-bevel | --lumo-xxx |
| v-bevel-depth | --lumo-xxx |
| v-shadow | --lumo-xxx |
| v-shadow-opacity | --lumo-xxx |
| v-focus-style | --lumo-xxx |
| v-disabled-opacity | --lumo-xxx |

### Table
| Valo | Lumo |
| --- | --- |
| v-table-row-height | --lumo-xxx |
| v-table-border-width | --lumo-xxx |
| v-table-border-color | --lumo-xxx |
| v-table-border-radius | --lumo-xxx |
| v-table-cell-padding-horizontal | --lumo-xxx |
| v-table-resizer-width | --lumo-xxx |
| v-table-sort-indicator-width | --lumo-xxx |
| v-table-header-font-size | --lumo-xxx |
| v-table-background-color | --lumo-xxx |

### General
| Valo | Lumo |
| --- | --- |
| v-loading-indicator-color | --lumo-xxx |
| v-loading-indicator-bar-height | --lumo-xxx |
| v-loading-indicator-bar-height--wait | --lumo-xxx |
| v-app-loading-text | --lumo-xxx |
| v-relative-paths | --lumo-xxx |

### Calendar
| Valo | Lumo |
| --- | --- |
| v-calendar-event-colors | --lumo-xxx |

### CssLayout
| Valo | Lumo |
| --- | --- |
| v-component-group-spacing | --lumo-xxx |

### Label
| Valo | Lumo |
| --- | --- |
| v-font-weight--header | --lumo-xxx |
| v-line-height--header | --lumo-xxx |
| v-font-family--header | --lumo-xxx |
| v-font-color--colored | --lumo-xxx |
| v-font-size--h1 | --lumo-xxx |
| v-font-size--h2 | --lumo-xxx |
| v-font-size--h3 | --lumo-xxx |
| v-font-family--h1 | --lumo-xxx |
| v-font-family--h2 | --lumo-xxx |
| v-font-family--h3 | --lumo-xxx |
| v-letter-spacing--h1 | --lumo-xxx |
| v-letter-spacing--h2 | --lumo-xxx |
| v-letter-spacing--h3 | --lumo-xxx |
| v-letter-spacing--h4 | --lumo-xxx |

### Link
| Valo | Lumo |
| --- | --- |
| v-link-font-color | --lumo-xxx |
| v-link-text-decoration | --lumo-xxx |
| v-link-cursor | --lumo-xxx |

### Notification
| Valo | Lumo |
| --- | --- |
| v-notification-title-color | --lumo-xxx |

### Overlay
| Valo | Lumo |
| --- | --- |
| v-overlay-background-color | --lumo-xxx |
| v-overlay-border-radius | --lumo-xxx |
| v-overlay-border-width | --lumo-xxx |
| v-overlay-animate-in | --lumo-xxx |
| v-overlay-animate-out | --lumo-xxx |
| v-overlay-padding | --lumo-xxx |
| v-overlay-padding-vertical | --lumo-xxx |
| v-overlay-padding-horizontal | --lumo-xxx |
| v-overlay-shadow | --lumo-xxx |
| v-selection-overlay-background-color | --lumo-xxx |
| v-selection-overlay-padding | --lumo-xxx |
| v-selection-overlay-padding-vertical | --lumo-xxx |
| v-selection-overlay-padding-horizontal | --lumo-xxx |
| v-selection-item-border-radius | --lumo-xxx |
| v-selection-item-height | --lumo-xxx |
| v-selection-item-padding-horizontal | --lumo-xxx |
| v-selection-item-font-weight | --lumo-xxx |
| v-selection-item-selection-color | --lumo-xxx |

### Panel
| Valo | Lumo |
| --- | --- |
| v-panel-background-color | --lumo-xxx |
| v-panel-border | --lumo-xxx |

### Progress Bar
| Valo | Lumo |
| --- | --- |
| v-progressbar-border-radius | --lumo-xxx |

### Rich Text Area
| Valo | Lumo |
| --- | --- |
| valo-richtextarea-use-font-awesome | --lumo-xxx |

### Slider
| Valo | Lumo |
| --- | --- |
| v-slider-track-size | --lumo-xxx |
| v-slider-track-border-radius | --lumo-xxx |
| v-slider-handle-width | --lumo-xxx |
| v-slider-handle-height | --lumo-xxx |
| v-slider-handle-border-radius | --lumo-xxx |
| _valo-slider-base-margin-vertical | --lumo-xxx |
| _valo-slider-base-margin-horizontal | --lumo-xxx |

### Tabsheet
| Valo | Lumo |
| --- | --- |
| v-tabsheet-content-animation-enabled | --lumo-xxx |

### Textfield
| Valo | Lumo |
| --- | --- |
| v-textfield-background-color | --lumo-xxx |
| v-textfield-background-color--readonly | --lumo-xxx |
| v-textfield-bevel | --lumo-xxx |
| v-textfield-shadow | --lumo-xxx |
| v-textfield-font-weight | --lumo-xxx |
| v-textfield-border | --lumo-xxx |
| v-textfield-border-radius | --lumo-xxx |
| v-textfield-disabled-opacity | --lumo-xxx |

### Tooltip
| Valo | Lumo |
| --- | --- |
| v-tooltip-background-color | --lumo-xxx |
| v-tooltip-font-color | --lumo-xxx |
| v-tooltip-font-size | --lumo-xxx |
| v-tooltip-box-shadow | --lumo-xxx |
| v-tooltip-padding-vertical | --lumo-xxx |
| v-tooltip-padding-horizontal | --lumo-xxx |
| v-tooltip-error-message-background-color | --lumo-xxx |
| v-tooltip-error-message-font-color | --lumo-xxx |
| v-tooltip-border-radius | --lumo-xxx |

### Tree
| Valo | Lumo |
| --- | --- |
| v-tree-row-height | --lumo-xxx |
| v-tree-animations-enabled | --lumo-xxx |
| v-tree-expand-animation-enabled | --lumo-xxx |

### Valo menu
| Valo | Lumo |
| --- | --- |
| valo-menu-background-color | --lumo-xxx |

### Window
| Valo | Lumo |
| --- | --- |
| v-window-background-color | --lumo-xxx |
| v-window-border-radius | --lumo-xxx |
| v-window-shadow | --lumo-xxx |
| v-window-animate-in | --lumo-xxx |
| v-window-animate-out | --lumo-xxx |
| v-window-modality-curtain-background-color | --lumo-xxx |

### Layout
| Valo | Lumo |
| --- | --- |
| v-unit-size | --lumo-xxx |
| v-scaling-factor--tiny | --lumo-xxx |
| v-scaling-factor--small | --lumo-xxx |
| v-scaling-factor--large | --lumo-xxx |
| v-scaling-factor--huge | --lumo-xxx |
| v-unit-size--tiny | --lumo-xxx |
| v-unit-size--small | --lumo-xxx |
| v-unit-size--large | --lumo-xxx |
| v-unit-size--huge | --lumo-xxx |
| v-layout-margin-top | --lumo-xxx |
| v-layout-margin-right | --lumo-xxx |
| v-layout-margin-bottom | --lumo-xxx |
| v-layout-margin-left | --lumo-xxx |
| v-layout-spacing-vertical | --lumo-xxx |
| v-layout-spacing-horizontal | --lumo-xxx |
| v-default-field-width | --lumo-xxx |

### Typography
| Valo | Lumo |
| --- | --- |
| v-line-height | --lumo-xxx |
| v-font-size | --lumo-xxx |
| v-font-weight | --lumo-xxx |
| v-font-family | --lumo-xxx |
| v-caption-font-size | --lumo-xxx |
| v-caption-font-weight | --lumo-xxx |
| v-font-size--tiny | --lumo-xxx |
| v-font-size--small | --lumo-xxx |
| v-font-size--large | --lumo-xxx |
| v-font-size--huge | --lumo-xxx |

**Comment by jouni** [comment]
Went through the research 👍 I made a couple of minor corrections.

**Comment by pleku** [comment]
For outsiders - to be seen if and when we do anything for this. It could make sense, but only after some parts of Lumo are changed first. If someone would need this, please just comment here and ping people if necessary.
