### ISSUE TITLE
Introduce Panel with caption + content

### ISSUE THREAD

**Issue by pleku** [vaadin/flow-legacy-components#73]
<html>
<body>

Return | Method
-- | --
  | Panel()Creates a new empty panel.
  | Panel(Component content)Creates a new empty panel which contains the given content.
  | Panel(String caption)Creates a new empty panel with caption.
  | Panel(String caption, Component content)Creates a new empty panel with the given caption and content.
Registration | addClickListener(MouseEvents.ClickListener listener)Add a click listener to the Panel.
String | getCaption()
int | getScrollLeft()Gets scroll left offset.
int | getScrollTop()Gets scroll top offset.
void | setCaption(String caption)Sets the caption of the component.
void | setScrollLeft(int scrollLeft)Sets scroll left offset.
void | setScrollTop(int scrollTop)Sets scroll top offset.

</body>
</html>

**Comment by DiegoCardoso** [comment]
Leaving `addClickListener` out of scope of this ticket. It will be introduced later.

**Comment by DiegoCardoso** [comment]
Closed by #93
