### ISSUE TITLE
Make default margin and spacing in layouts easily configurable

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/flow-legacy-components#92]
V8 had margins and spacing on by default, while V7 had them off by default.
In order to support easy migration from both, the margin (padding) and spacing (gap) in legacy layout components should be easy to configure to either default.

Proposal: use legacy layout specific css variables for them, e.g. something like this:
```
--legacy-layout-default-margin: var(--lumo-space-m);
--legacy-layout-default-spacing: var(--lumo-space-m);

```
That way, in a V7 migration project these can be overriden to 0.

Explicitly enabling spacing or margin should of course then override this back to `--lumo-space-m`.

**Comment by pleku** [comment]
Like discussed, we should introduce it as a configuration parameter through Java so then the component state and class names go correctly. This configuration parameter needs to be added to documentation too.
